file(READ "${HTML_INPUT}" HTML_CONTENT)
file(WRITE "${CPP_OUTPUT}"
"// Auto-generated by CMake — do not edit.\n// Source: web/index.html\nconst char* HTML_CONTENT = R\"HTML(${HTML_CONTENT})HTML\";\n"
)
